/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafor2023;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Imtiaz Adar
 */
public class ClockImtiazAdar extends javax.swing.JFrame implements Runnable {

    public ClockImtiazAdar() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        Thread t1 = new Thread(this);
        t1.start();
        initComponents();
        this.getContentPane().setBackground(new Color(20, 20, 20));
        icon = new ImageIcon(getClass().getResource("time.png"));
        this.setIconImage(icon.getImage());
        
        date = new Date();
        time = new SimpleDateFormat("HH:mm:ss a");
        timeVariable.setText(time.format(date));
        String path = "C:\\Users\\imtia\\OneDrive\\Documents\\NetBeansProjects\\JavaFor2023\\src\\javafor2023\\inspire.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        clip = AudioSystem.getClip();
        clip.open(audio);
        playLoop();
        
    }
    public void playLoop(){
        clip.loop(Clip.LOOP_CONTINUOUSLY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        timeVariable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIGITAL CLOCK BY IMTIAZ ADAR");
        setBackground(new java.awt.Color(20, 20, 20));
        setForeground(new java.awt.Color(0, 0, 0));
        setName("frame"); // NOI18N
        setResizable(false);

        timeVariable.setBackground(new java.awt.Color(0, 0, 0));
        timeVariable.setFont(new java.awt.Font("DS-Digital", 1, 100)); // NOI18N
        timeVariable.setForeground(java.awt.Color.cyan);
        timeVariable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeVariable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 80)); // NOI18N
        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setText("CLOCK BY IMTIAZ ADAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(timeVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClockImtiazAdar().setVisible(true);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(ClockImtiazAdar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ClockImtiazAdar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(ClockImtiazAdar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    @Override
    public void run(){
        //timeVariable.setText("Imtiaz");
        while(status){
            //System.out.println("HI");
            date = new Date();
            time = new SimpleDateFormat("HH:mm:ss a");
            timeVariable.setText(time.format(date));
            try{
                Thread.sleep(1000);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel timeVariable;
    // End of variables declaration//GEN-END:variables
    public SimpleDateFormat time;
    public Date date;
    public boolean status = true;
    public Clip clip;
    public ImageIcon icon;
}
